version: "3.8"

services:
  solidjs-frontend:
    image: ghcr.io/vveil/zahnarztweb.frontend:latest

  node-backend:
    image: ghcr.io/vveil/zahnarztweb.backend:latest
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

networks:
  webnet:
    external: true
