version: "3.8"

services:
  zahnarztweb:
    image: ghcr.io/vveil/zahnarztweb.frontend:latest
    labels:
      - "traefik.http.routers.zahnarztweb.rule=Host(`dr-werner-zahnarzt.de`)"
        #    networks:
        #      - webnet

  # node-backend:
  #   image: ghcr.io/vveil/zahnarztweb.backend:latest
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./backend/uploads:/usr/src/app/uploads

        #networks:
        #webnet:
        #    external: true
