version: "3.8"

services:
  solidjs-frontend:
    image: ghcr.io/vveil/zahnarztweb.frontend:latest
    networks:
      - webnet

  # node-backend:
  #   image: ghcr.io/vveil/zahnarztweb.backend:latest
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./backend/uploads:/usr/src/app/uploads

networks:
  webnet:
    external: true
