version: "3.8"

services:
  solidjs-frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
        #    ports:
        #- "3000:3000"

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
