version: "3.8"

services:
  solidjs-frontend:
    image: ghcr.io/vveil/zahnarztweb.frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    #    ports:
    #- "3000:3000"

  node-backend:
    image: ghcr.io/vveil/zahnarztweb.backend:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    # ports:
    #   - "3001:3001"

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
